FROM apache/airflow:2.8.1-python3.9

# 3. Switch back to airflow user
USER airflow

# 4. Set working directory and install Python packages
WORKDIR /opt/airflow
COPY requirements.txt .
USER airflow
RUN pip install --no-cache-dir "dbt-core==1.9.1" "dbt-postgres==1.9.1"
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en_core_web_sm

# 6. Copy your scripts
COPY ./scripts ./scripts