version: 2
models:
  - name: stg_statcast
    description: "statcast pitches from bronze.statcast"
    columns:
      - name: pitch_id
        tests: [not_null, unique]
      - name: game_pk
        tests: [not_null]
      - name: at_bat_number
        tests: [not_null]
      - name: pitch_number
        tests: [not_null]

  - name: stg_transactions
    description: 'transactions from bronze.transactions'
    columns:
      - name: trans_id
        tests: [not_null, unique]

  - name: stg_games
    description: 'games from bronze.games'
    columns:
      - name: gamepk
        tests: [not_null, unique]
  
  - name: stg_teams
    description: 'team information from bronze.teams'
    columns:
      - name: 'team_id'
        tests: [not_null, unique]
  
  - name: stg_roster_entries
    columns:
      - name: roster_sk
        tests: [not_null, unique]

  - name: stg_injury_spans
    columns:
    - name: injury_sk
      tests: [not_null, unique]
    tests:
    - dbt_utils.mutually_exclusive_ranges:
        lower_bound_column: il_place_date
        # If return_date can be NULL, treat it as open-ended:
        upper_bound_column: "coalesce(return_date, '9999-12-31')"
        partition_by: person_id